version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:13.3-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
