
exports.up = knex => knex.schema.createTable('information_amount', table => {
    table
        .increments('id');
    table 
        .integer('user_id')
        .notNull();
    table
        .integer('points')
        .default(0);
    table
        .integer('weekly_points')
        .default(0);
    table
        .integer('level')
        .default(0);
    table
        .integer('evaluations')
        .defaultTo(0);
    table
        .integer('edit_evaluations')
        .defaultTo(0);
    table
        .integer('public_evaluations')
        .defaultTo(0);
    table
        .integer('private_evaluations')
        .defaultTo(0);
    table
        .integer('accessible_place')
        .defaultTo(0);
    table
        .integer('not_accessible_place')
        .defaultTo(0);
    table
        .integer('partially_accessible_place')
        .defaultTo(0);
    table
        .integer('place')
        .defaultTo(0);
    table
        .integer('wheelchair_parking')
        .defaultTo(0);
    table
        .integer('travel')
        .defaultTo(0);
    table
        .integer('transport')
        .defaultTo(0);
    table
        .integer('supermarket')
        .defaultTo(0);
    table
        .integer('services')
        .defaultTo(0);
    table
        .integer('leisure')
        .defaultTo(0);
    table
        .integer('education')
        .defaultTo(0);
    table
        .integer('food')
        .defaultTo(0);
    table
        .integer('hospital')
        .defaultTo(0);
    table
        .integer('accomodation')
        .defaultTo(0);
    table
        .integer('finance')
        .defaultTo(0);
    table
        .integer('comments')
        .defaultTo(0);
    table
        .dateTime('created_at')
        .notNull()
        .defaultTo(knex.raw('now()'));
    table
        .dateTime('updated_at')
        .notNull()
        .defaultTo(knex.raw('now()'));
    table
        .dateTime('deleted_at')
        .defaultTo(null);
})
.table('information_amount', table => {
    table
        .foreign('user_id')
        .references('id')
        .inTable('users');
});

exports.down = knex => knex.schema.dropTable('information_amount');